//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\I525976\source\repos\HexRuntimeAssemblier\HexRuntimeAssemblier\.antlr\Assemblier.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAssemblierListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class AssemblierBaseListener : IAssemblierListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] Assemblier.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] Assemblier.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodArgument([NotNull] Assemblier.MethodArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodArgument([NotNull] Assemblier.MethodArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodArgumentList([NotNull] Assemblier.MethodArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodArgumentList([NotNull] Assemblier.MethodArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodReturnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodReturnType([NotNull] Assemblier.MethodReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodReturnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodReturnType([NotNull] Assemblier.MethodReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodName([NotNull] Assemblier.MethodNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodName([NotNull] Assemblier.MethodNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodImport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodImport([NotNull] Assemblier.MethodImportContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodImport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodImport([NotNull] Assemblier.MethodImportContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodSource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodSource([NotNull] Assemblier.MethodSourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodSource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodSource([NotNull] Assemblier.MethodSourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodLocal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodLocal([NotNull] Assemblier.MethodLocalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodLocal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodLocal([NotNull] Assemblier.MethodLocalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodLocals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodLocals([NotNull] Assemblier.MethodLocalsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodLocals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodLocals([NotNull] Assemblier.MethodLocalsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCode([NotNull] Assemblier.MethodCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCode([NotNull] Assemblier.MethodCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodIl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodIl([NotNull] Assemblier.MethodIlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodIl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodIl([NotNull] Assemblier.MethodIlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodOpcodeOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodOpcodeOperand([NotNull] Assemblier.MethodOpcodeOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodOpcodeOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodOpcodeOperand([NotNull] Assemblier.MethodOpcodeOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodBody([NotNull] Assemblier.MethodBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodBody([NotNull] Assemblier.MethodBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDef([NotNull] Assemblier.MethodDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDef([NotNull] Assemblier.MethodDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodRef([NotNull] Assemblier.MethodRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodRef([NotNull] Assemblier.MethodRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.fieldDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDef([NotNull] Assemblier.FieldDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.fieldDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDef([NotNull] Assemblier.FieldDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.fieldRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldRef([NotNull] Assemblier.FieldRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.fieldRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldRef([NotNull] Assemblier.FieldRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertyGet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyGet([NotNull] Assemblier.PropertyGetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertyGet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyGet([NotNull] Assemblier.PropertyGetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertySet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertySet([NotNull] Assemblier.PropertySetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertySet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertySet([NotNull] Assemblier.PropertySetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyDef([NotNull] Assemblier.PropertyDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyDef([NotNull] Assemblier.PropertyDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeRefList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeRefList([NotNull] Assemblier.TypeRefListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeRefList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeRefList([NotNull] Assemblier.TypeRefListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.implementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplementList([NotNull] Assemblier.ImplementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.implementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplementList([NotNull] Assemblier.ImplementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] Assemblier.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] Assemblier.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArray([NotNull] Assemblier.TypeArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArray([NotNull] Assemblier.TypeArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeNestArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNestArray([NotNull] Assemblier.TypeNestArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeNestArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNestArray([NotNull] Assemblier.TypeNestArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeMultidimensionArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeMultidimensionArray([NotNull] Assemblier.TypeMultidimensionArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeMultidimensionArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeMultidimensionArray([NotNull] Assemblier.TypeMultidimensionArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeInteriorRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeInteriorRef([NotNull] Assemblier.TypeInteriorRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeInteriorRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeInteriorRef([NotNull] Assemblier.TypeInteriorRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeRef([NotNull] Assemblier.TypeRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeRef([NotNull] Assemblier.TypeRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] Assemblier.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] Assemblier.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] Assemblier.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] Assemblier.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDef([NotNull] Assemblier.ClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDef([NotNull] Assemblier.ClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyValue([NotNull] Assemblier.PropertyValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyValue([NotNull] Assemblier.PropertyValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertyKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyKey([NotNull] Assemblier.PropertyKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertyKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyKey([NotNull] Assemblier.PropertyKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] Assemblier.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] Assemblier.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.assemblyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyDef([NotNull] Assemblier.AssemblyDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.assemblyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyDef([NotNull] Assemblier.AssemblyDefContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
