//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\I525976\source\repos\HexJacaranda\HexRuntimeAssemblier\HexRuntimeAssemblier\.antlr\Assemblier.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAssemblierListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class AssemblierBaseListener : IAssemblierListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] Assemblier.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] Assemblier.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.modifierAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifierAccess([NotNull] Assemblier.ModifierAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.modifierAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifierAccess([NotNull] Assemblier.ModifierAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.modifierLife"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifierLife([NotNull] Assemblier.ModifierLifeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.modifierLife"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifierLife([NotNull] Assemblier.ModifierLifeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodArgument([NotNull] Assemblier.MethodArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodArgument([NotNull] Assemblier.MethodArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodArgumentList([NotNull] Assemblier.MethodArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodArgumentList([NotNull] Assemblier.MethodArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodReturnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodReturnType([NotNull] Assemblier.MethodReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodReturnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodReturnType([NotNull] Assemblier.MethodReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodName([NotNull] Assemblier.MethodNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodName([NotNull] Assemblier.MethodNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodImport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodImport([NotNull] Assemblier.MethodImportContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodImport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodImport([NotNull] Assemblier.MethodImportContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodSource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodSource([NotNull] Assemblier.MethodSourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodSource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodSource([NotNull] Assemblier.MethodSourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodLocal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodLocal([NotNull] Assemblier.MethodLocalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodLocal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodLocal([NotNull] Assemblier.MethodLocalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodLocals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodLocals([NotNull] Assemblier.MethodLocalsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodLocals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodLocals([NotNull] Assemblier.MethodLocalsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCode([NotNull] Assemblier.MethodCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCode([NotNull] Assemblier.MethodCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodProperty([NotNull] Assemblier.MethodPropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodProperty([NotNull] Assemblier.MethodPropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodBody([NotNull] Assemblier.MethodBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodBody([NotNull] Assemblier.MethodBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDef([NotNull] Assemblier.MethodDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDef([NotNull] Assemblier.MethodDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.methodRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodRef([NotNull] Assemblier.MethodRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.methodRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodRef([NotNull] Assemblier.MethodRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.fieldDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDef([NotNull] Assemblier.FieldDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.fieldDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDef([NotNull] Assemblier.FieldDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.fieldRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldRef([NotNull] Assemblier.FieldRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.fieldRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldRef([NotNull] Assemblier.FieldRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertyGet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyGet([NotNull] Assemblier.PropertyGetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertyGet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyGet([NotNull] Assemblier.PropertyGetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertySet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertySet([NotNull] Assemblier.PropertySetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertySet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertySet([NotNull] Assemblier.PropertySetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyDef([NotNull] Assemblier.PropertyDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyDef([NotNull] Assemblier.PropertyDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.eventAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventAdd([NotNull] Assemblier.EventAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.eventAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventAdd([NotNull] Assemblier.EventAddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.eventRemove"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventRemove([NotNull] Assemblier.EventRemoveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.eventRemove"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventRemove([NotNull] Assemblier.EventRemoveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.eventDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventDef([NotNull] Assemblier.EventDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.eventDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventDef([NotNull] Assemblier.EventDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.inheritOrImplementType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInheritOrImplementType([NotNull] Assemblier.InheritOrImplementTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.inheritOrImplementType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInheritOrImplementType([NotNull] Assemblier.InheritOrImplementTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeRefList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeRefList([NotNull] Assemblier.TypeRefListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeRefList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeRefList([NotNull] Assemblier.TypeRefListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.implementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplementList([NotNull] Assemblier.ImplementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.implementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplementList([NotNull] Assemblier.ImplementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeInherit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeInherit([NotNull] Assemblier.TypeInheritContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeInherit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeInherit([NotNull] Assemblier.TypeInheritContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.assemblyRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyRef([NotNull] Assemblier.AssemblyRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.assemblyRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyRef([NotNull] Assemblier.AssemblyRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] Assemblier.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] Assemblier.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.typeRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeRef([NotNull] Assemblier.TypeRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.typeRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeRef([NotNull] Assemblier.TypeRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] Assemblier.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] Assemblier.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.genericParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericParameterList([NotNull] Assemblier.GenericParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.genericParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericParameterList([NotNull] Assemblier.GenericParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] Assemblier.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] Assemblier.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.genericInstantiation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericInstantiation([NotNull] Assemblier.GenericInstantiationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.genericInstantiation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericInstantiation([NotNull] Assemblier.GenericInstantiationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.genericParameterRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericParameterRef([NotNull] Assemblier.GenericParameterRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.genericParameterRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericParameterRef([NotNull] Assemblier.GenericParameterRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] Assemblier.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] Assemblier.ArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.nestArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestArrayType([NotNull] Assemblier.NestArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.nestArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestArrayType([NotNull] Assemblier.NestArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.multidimensionArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultidimensionArrayType([NotNull] Assemblier.MultidimensionArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.multidimensionArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultidimensionArrayType([NotNull] Assemblier.MultidimensionArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.interiorRefType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteriorRefType([NotNull] Assemblier.InteriorRefTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.interiorRefType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteriorRefType([NotNull] Assemblier.InteriorRefTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.genericList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericList([NotNull] Assemblier.GenericListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.genericList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericList([NotNull] Assemblier.GenericListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] Assemblier.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] Assemblier.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDef([NotNull] Assemblier.ClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDef([NotNull] Assemblier.ClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyValue([NotNull] Assemblier.PropertyValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyValue([NotNull] Assemblier.PropertyValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.propertyKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyKey([NotNull] Assemblier.PropertyKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.propertyKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyKey([NotNull] Assemblier.PropertyKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] Assemblier.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] Assemblier.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.assemblyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyDef([NotNull] Assemblier.AssemblyDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.assemblyDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyDef([NotNull] Assemblier.AssemblyDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLabel([NotNull] Assemblier.OpLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLabel([NotNull] Assemblier.OpLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdFld"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdFld([NotNull] Assemblier.OpLdFldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdFld"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdFld([NotNull] Assemblier.OpLdFldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdFldA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdFldA([NotNull] Assemblier.OpLdFldAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdFldA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdFldA([NotNull] Assemblier.OpLdFldAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdLoc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdLoc([NotNull] Assemblier.OpLdLocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdLoc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdLoc([NotNull] Assemblier.OpLdLocContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdLocA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdLocA([NotNull] Assemblier.OpLdLocAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdLocA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdLocA([NotNull] Assemblier.OpLdLocAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdArg([NotNull] Assemblier.OpLdArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdArg([NotNull] Assemblier.OpLdArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdArgA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdArgA([NotNull] Assemblier.OpLdArgAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdArgA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdArgA([NotNull] Assemblier.OpLdArgAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdElem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdElem([NotNull] Assemblier.OpLdElemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdElem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdElem([NotNull] Assemblier.OpLdElemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdElemA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdElemA([NotNull] Assemblier.OpLdElemAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdElemA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdElemA([NotNull] Assemblier.OpLdElemAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdStr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdStr([NotNull] Assemblier.OpLdStrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdStr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdStr([NotNull] Assemblier.OpLdStrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpConstant([NotNull] Assemblier.OpConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpConstant([NotNull] Assemblier.OpConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdC([NotNull] Assemblier.OpLdCContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdC([NotNull] Assemblier.OpLdCContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdFn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdFn([NotNull] Assemblier.OpLdFnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdFn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdFn([NotNull] Assemblier.OpLdFnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opLdNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLdNull([NotNull] Assemblier.OpLdNullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opLdNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLdNull([NotNull] Assemblier.OpLdNullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opStFld"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpStFld([NotNull] Assemblier.OpStFldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opStFld"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpStFld([NotNull] Assemblier.OpStFldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opStLoc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpStLoc([NotNull] Assemblier.OpStLocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opStLoc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpStLoc([NotNull] Assemblier.OpStLocContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opStArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpStArg([NotNull] Assemblier.OpStArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opStArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpStArg([NotNull] Assemblier.OpStArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opStElem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpStElem([NotNull] Assemblier.OpStElemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opStElem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpStElem([NotNull] Assemblier.OpStElemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opStTA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpStTA([NotNull] Assemblier.OpStTAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opStTA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpStTA([NotNull] Assemblier.OpStTAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpAdd([NotNull] Assemblier.OpAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpAdd([NotNull] Assemblier.OpAddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpSub([NotNull] Assemblier.OpSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpSub([NotNull] Assemblier.OpSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opMul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpMul([NotNull] Assemblier.OpMulContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opMul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpMul([NotNull] Assemblier.OpMulContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opDiv"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpDiv([NotNull] Assemblier.OpDivContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opDiv"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpDiv([NotNull] Assemblier.OpDivContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpMod([NotNull] Assemblier.OpModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpMod([NotNull] Assemblier.OpModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpAnd([NotNull] Assemblier.OpAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpAnd([NotNull] Assemblier.OpAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpOr([NotNull] Assemblier.OpOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpOr([NotNull] Assemblier.OpOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opXor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpXor([NotNull] Assemblier.OpXorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opXor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpXor([NotNull] Assemblier.OpXorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpNot([NotNull] Assemblier.OpNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpNot([NotNull] Assemblier.OpNotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opNeg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpNeg([NotNull] Assemblier.OpNegContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opNeg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpNeg([NotNull] Assemblier.OpNegContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opConv"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpConv([NotNull] Assemblier.OpConvContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opConv"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpConv([NotNull] Assemblier.OpConvContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpCall([NotNull] Assemblier.OpCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpCall([NotNull] Assemblier.OpCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opCallVirt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpCallVirt([NotNull] Assemblier.OpCallVirtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opCallVirt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpCallVirt([NotNull] Assemblier.OpCallVirtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opRet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpRet([NotNull] Assemblier.OpRetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opRet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpRet([NotNull] Assemblier.OpRetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opCmpCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpCmpCond([NotNull] Assemblier.OpCmpCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opCmpCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpCmpCond([NotNull] Assemblier.OpCmpCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opCmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpCmp([NotNull] Assemblier.OpCmpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opCmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpCmp([NotNull] Assemblier.OpCmpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opJcc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpJcc([NotNull] Assemblier.OpJccContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opJcc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpJcc([NotNull] Assemblier.OpJccContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opJmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpJmp([NotNull] Assemblier.OpJmpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opJmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpJmp([NotNull] Assemblier.OpJmpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opThrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpThrow([NotNull] Assemblier.OpThrowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opThrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpThrow([NotNull] Assemblier.OpThrowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opTry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpTry([NotNull] Assemblier.OpTryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opTry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpTry([NotNull] Assemblier.OpTryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opCatch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpCatch([NotNull] Assemblier.OpCatchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opCatch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpCatch([NotNull] Assemblier.OpCatchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opFinally"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpFinally([NotNull] Assemblier.OpFinallyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opFinally"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpFinally([NotNull] Assemblier.OpFinallyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opNew"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpNew([NotNull] Assemblier.OpNewContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opNew"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpNew([NotNull] Assemblier.OpNewContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opNewArr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpNewArr([NotNull] Assemblier.OpNewArrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opNewArr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpNewArr([NotNull] Assemblier.OpNewArrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opDup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpDup([NotNull] Assemblier.OpDupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opDup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpDup([NotNull] Assemblier.OpDupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opPop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpPop([NotNull] Assemblier.OpPopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opPop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpPop([NotNull] Assemblier.OpPopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.opNop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpNop([NotNull] Assemblier.OpNopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.opNop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpNop([NotNull] Assemblier.OpNopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assemblier.ilInstruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIlInstruction([NotNull] Assemblier.IlInstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assemblier.ilInstruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIlInstruction([NotNull] Assemblier.IlInstructionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
